# Set the base image
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base

# Set the working directory inside the container
WORKDIR /app

# Copy the published application files to the container
COPY /GeoPerdasCloud.ProgGeoPerdasConsole/bin/Release/net6.0/publish/ .

# Define the entry point for the container
ENTRYPOINT ["dotnet", "GeoPerdasCloud.ProgGeoPerdasConsole.dll"]